### ISSUE TITLE
systemd[1]: Failed to start Transition between telemd and telempostd.

### ISSUE THREAD

**Issue by jeremiah** [clearlinux/telemetrics-client#77] opened 2018-12-03 21:17 UTC
I get this error starting up.

**Comment by alexjch** [comment] 2018-12-03 23:52
What flavor of Linux are you using?
Are you using systemdctl or telemctl.

**Comment by jeremiah** [comment] 2018-12-04 00:05
Thanks for the reply.

I'm using Clear Linux VERSION_ID=26630
And I have telemctl on my system but no systemdctl (typo?).

**Comment by clsulliv** [comment] 2018-12-14 20:39
I think this is caused by this line in the telemd-update-trigger.service file:
`ExecStartPre=/usr/bin/systemctl stop telemd.service`

This file is actually coming from the telemetrics-client package repo rather than this repo:
https://github.com/clearlinux-pkgs/telemetrics-client/blob/master/telemd-update-trigger.service

I take it this was added to aid in the split of telemd into telempostd/telemprobd, and may still be necessary on old installations. I think the error is harmless, but perhaps it should only be ran if the telemd.service file exists?

**Comment by jeremiah** [comment] 2018-12-18 16:42
I have /usr/lib/systemd/system/telemd-update-trigger.service on my system and it has those contents.

**Comment by alexjch** [comment] 2018-12-18 16:47
The error is harmless as clsulliv explained, but it is a bug nonetheless. Will work on a fix. Thanks for reporting this error.

**Comment by jurobystricky** [comment] 2019-07-20 14:52
Closing because the telemetrics-client release 2.2.0 removed the telemd-update-trigger.service (obsoleted), so this message will not show up again.

**Closed by jurobystricky** 2019-07-20 14:52 UTC
